### ISSUE TITLE
java.io.IOException: Is a directory

### ISSUE THREAD

**Issue by torbjornvatn** [bizreach/aws-s3-scala#4]
I'm using `S3.local` to unit test my S3 upload mechanism, but when I changed the key parameter to the `put()` method to be a contain a directory like this `s3.put(new Bucket(to.uploadFilePath), s"dt=$dt/${zipFile.getName}", zipFile)`, I get this strange exception:

`java.io.IOException: Is a directory
    at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
    at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:197)
    at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
    at java.io.InputStream.read(InputStream.java:101)
    at jp.co.bizreach.s3scala.IOUtils$.toBytes(IOUtils.scala:35)
    at jp.co.bizreach.s3scala.LocalS3Client$$anonfun$jp$co$bizreach$s3scala$LocalS3Client$$createObjectSummaries$1$$anon$2.<init>(LocalS3Client.scala:168)``

It seems that the problem is this section `length = in.read(buf)` on line 35 of `IOUtils.scala`

I'm running the code on a Mac with Java 1.8.0_66

**Comment by torbjornvatn** [comment]
Actually it was the `keys()` method on the bucket that caused the error, so when I changed to `keys(dt=$dt)`, passing in the key prefix instead, it worked
